# Análisis exploratorio de datos (EDA): evolución de las ventas y rentabilidad de una cadena de tiendas de chocolate

El objetivo de este proyecto es realizar un análisis exploratorio de datos sobre las ventas de una cadena de tiendas de chocolate durante noviembre y diciembre de 2023. Para ello se llevará a cabo un proceso de exploración, limpieza, transformación e integración de datos utilizando Python y las bibliotecas especializadas en análisis de datos.

El análisis buscará identificar patrones de ventas, evaluar la evolución de los ingresos y la rentabilidad entre ambos meses, comparar el rendimiento de las tiendas y estudiar el comportamiento de los clientes.

## 1. IMPORTACIÓN DE LIBRERÍAS

En esta sección se importan las bibliotecas necesarias para la manipulación, el análisis y la visualización de los datos:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 2. CARGA DE DATOS

Luego de importar las librerias a utilizar en el proyecto, vamos a cargar los dataset a analizar. Los archivos se conservarán sin modificaciones en la carpeta de datos originales (`data/raw/`). A partir de ellos se crearán los DataFrames que se utilizarán durante las etapas de exploración, limpieza e integración.

In [2]:
sales_df = pd.read_csv("../data/raw/sales_nov-dec_2023.csv")
customers_df = pd.read_csv("../data/raw/customers.csv")
stores_df = pd.read_csv("../data/raw/stores.csv")

## 3. EXPLORACIÓN INICIAL

En este apartado, el objetivo es tener una imágen clara sobre los datasets, sus columnas, valores y formatos, para poder realizar la limpieza correspondiente. Para ello, usamos funcionemos como head, info, describe. En este punto, también podemos detectar la cantidad de nulos por columna con los que vamos a trabajar, y así determinar el tratamiento que se le dará a cada uno.

In [3]:
sales_df.columns

Index(['order_id', 'order_date', 'product_id', 'store_id', 'customer_id',
       'quantity', 'unit_price', 'discount', 'revenue', 'cost', 'profit'],
      dtype='object')

In [4]:
customers_df.columns

Index(['customer_id', 'age', 'gender', 'loyalty_member', 'join_date'], dtype='object')

In [5]:
stores_df.columns

Index(['store_id', 'store_name', 'city', 'country', 'store_type'], dtype='object')

In [6]:
sales_df.shape

(83129, 11)

In [7]:
customers_df.shape

(50000, 5)

In [8]:
stores_df.shape

(100, 5)

In [9]:
sales_df.head()

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000669,2023-11-01,P0178,S060,C017791,3,10.11,0.00,30.33,16.36,13.97
1,0RD00001268,2023-11-01,P0051,NaN,C000973,2,6.26,0.00,12.52,6.37,6.15
2,0RD00002218,2023-11-01,P0135,S016,C040731,4,7.21,0.15,24.51,15.88,8.63
3,0RD00002513,2023-11-01,P0135,S025,C021877,4,NaN,0.00,46.44,30.08,16.36
4,0RD00003231,2023-11-01,P0054,S011,C012499,1,3.34,0.15,2.84,1.77,1.07

In [10]:
sales_df.tail()

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
83124,0RD00996434,2023-dic-31,P0012,S036,C007793,5,8.62,0.00,43.10,27.07,16.03
83125,0RD00996886,2023-dic-31,P0008,S003,C018157,2,7.46,0.10,13.43,7.88,5.54
83126,0RD00998419,2023-dic-31,P0156,S042,C048247,4,14.61,0.00,58.44,36.39,22.05
83127,0RD00999419,2023-dic-31,P0115,S059,C006766,3,14.02,0.15,35.75,25.00,10.75
83128,0RD00999925,2023-dic-31,P0059,S087,C015062,3,4.55,0.20,10.92,7.01,3.91

In [11]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83129 entries, 0 to 83128
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     83129 non-null  object
 1   order_date   83129 non-null  object
 2   product_id   83129 non-null  object
 3   store_id     83116 non-null  object
 4   customer_id  83129 non-null  object
 5   quantity     83129 non-null  int64
 6   unit_price   83077 non-null  float64
 7   discount     83129 non-null  float64
 8   revenue      83129 non-null  float64
 9   cost         83129 non-null  float64
 10  profit       83129 non-null  float64
dtypes: float64(5), int64(1), object(5)
memory usage: 7.0+ MB

In [12]:
customers_df.head()

  customer_id  age  gender  loyalty_member   join_date
0     C000001   40    Male               1  2025-05-21
1     C000002   47    Male               0  2021-12-26
2     C000003   58  Female               1  2022-09-13
3     C000004   25  Female               0  2025-02-27
4     C000005   43    Male               0  2023-08-31

In [13]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     50000 non-null  object
 1   age             50000 non-null  int64
 2   gender          50000 non-null  object
 3   loyalty_member  50000 non-null  int64
 4   join_date       50000 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.9+ MB

In [14]:
stores_df.head()

  store_id         store_name      city country store_type
0     S001  Chocolate Store 1  New York  Canada     Retail
1     S002                NaN    Sydney  Canada       Mall
2     S003  Chocolate Store 3    Berlin  France       Mall
3     S004  Chocolate Store 4     Paris      UK    Airport
4     S005  Chocolate Store 5    Sydney     USA     Online

In [15]:
stores_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    100 non-null    object
 1   store_name  95 non-null     object
 2   city        100 non-null    object
 3   country     100 non-null    object
 4   store_type  100 non-null    object
dtypes: object(5)
memory usage: 4.0+ KB

In [16]:
sales_df.describe()

,quantity,unit_price,discount,revenue,cost,profit
count,83129.000000,83077.000000,83129.000000,83129.000000,83129.000000,83129.000000
mean,2.999266,9.009504,0.055906,25.500901,15.298831,10.202051
std,1.413716,3.450922,0.076734,16.333085,9.953694,6.759520
min,1.000000,3.000000,0.000000,2.400000,1.210000,0.730000
25%,2.000000,6.010000,0.000000,12.200000,7.250000,4.790000
50%,3.000000,9.020000,0.000000,21.950000,13.050000,8.620000
75%,4.000000,11.980000,0.100000,35.920000,21.460000,14.190000
max,5.000000,15.000000,0.200000,75.000000,52.230000,37.170000

In [17]:
customers_df.describe()

                age  loyalty_member
count  50000.000000    50000.000000
mean      44.026100        0.502080
std       15.328333        0.500001
min       18.000000        0.000000
25%       31.000000        0.000000
50%       44.000000        1.000000
75%       57.000000        1.000000
max       70.000000        1.000000

In [18]:
stores_df.describe()

       store_id         store_name    city country store_type
count       100                 95     100     100        100
unique      100                 95       6       6          4
top        S001  Chocolate Store 1  Sydney  Canada    Airport
freq          1                  1      25      20         30

In [19]:
sales_df[sales_df.duplicated()]

Empty DataFrame
Columns: [order_id, order_date, product_id, store_id, customer_id, quantity, unit_price, discount, revenue, cost, profit]
Index: []

In [20]:
customers_df[customers_df.duplicated()]

Empty DataFrame
Columns: [customer_id, age, gender, loyalty_member, join_date]
Index: []

In [21]:
stores_df[stores_df.duplicated()]

Empty DataFrame
Columns: [store_id, store_name, city, country, store_type]
Index: []

In [22]:
sales_df.isnull().sum()

order_id        0
order_date      0
product_id      0
store_id       13
customer_id     0
quantity        0
unit_price     52
discount        0
revenue         0
cost            0
profit          0
dtype: int64

In [23]:
customers_df.isnull().sum()

customer_id       0
age               0
gender            0
loyalty_member    0
join_date         0
dtype: int64

In [24]:
stores_df.isnull().sum()

store_id      0
store_name    5
city          0
country       0
store_type    0
dtype: int64

In [25]:

# Resumen de dimensiones de los datasets

print("Dimensiones de las tablas:")
print(f"Ventas: {sales_df.shape}")
print(f"Tiendas: {stores_df.shape}")
print(f"Clientes: {customers_df.shape}")

Dimensiones de las tablas:
Ventas: (83129, 11)
Tiendas: (100, 5)
Clientes: (50000, 5)

## 4. LIMPIEZA INICIAL

En esta etapa se revisarán y corregirán los tipos de datos, los formatos y las inconsistencias detectadas durante la exploración inicial. Se conservarán los datasets originales y se trabajará sobre copias para garantizar la trazabilidad de las transformaciones.

In [26]:
sales_clean = sales_df.copy()
customers_clean = customers_df.copy()
stores_clean = stores_df.copy()

4.1. Corrección de formatos

In [ ]:
# Unificar el formato de las fechas de ventas del dataset "sales"
sales_clean["order_date"] = (
    sales_clean["order_date"]
    .str.replace("-dic-", "-12-", regex=False)
)

sales_clean["order_date"] = pd.to_datetime(
    sales_clean["order_date"],
    format="%Y-%m-%d",
    errors="coerce"
)

In [ ]:
# Verificar el tipo de dato de la columna "order_date" y la cantidad de fechas no convertidas
print(sales_clean["order_date"].dtype)
print("Fechas no convertidas:", sales_clean["order_date"].isna().sum())

datetime64[ns]
Fechas no convertidas: 0

In [ ]:
# Unificar el formato de las fechas de dataset clientes del dataset "customers"

customers_clean["join_date"] = pd.to_datetime(
    customers_clean["join_date"],
    format="%Y-%m-%d",
    errors="coerce"
)

In [ ]:
# Verificar el tipo de dato de la columna "join_date"

print(customers_clean["join_date"].dtype)

datetime64[ns]

4.2. Tratamiento de valores nulos

In [ ]:
# Comprobar los registros con "unit_price" nulo

missing_price = sales_clean["unit_price"].isna()

# Verificar que todos tengan descuento igual a cero

sales_clean.loc[
    missing_price, "discount"
].value_counts(dropna=False)

discount
0.0    52
Name: count, dtype: int64

In [ ]:
# Verificar si algun valor de la columna "quantity" es igual a 0

sales_clean.loc[
    sales_clean["unit_price"].isna(), "quantity"
].le(0).sum()

np.int64(0)

In [34]:
# Como el "unit_price" es el resultado del cociente entre "revenue" y "quantity", podemos calcularlo para los registros que tienen "unit_price" nulo. No tenemos el descuento en cuenta ya que el mismo es igual a 0 en todos los registros con "unit_price" nulo.

missing_price = sales_clean["unit_price"].isna()

sales_clean.loc[missing_price, "unit_price"] = (
    sales_clean.loc[missing_price, "revenue"]
    / sales_clean.loc[missing_price, "quantity"]
)

print("Valores nulos restantes en unit_price:",
      sales_clean["unit_price"].isna().sum())

Valores nulos restantes en unit_price: 0